# Generated by Django 5.0.1 on 2024-02-19 07:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(help_text='Portfolio primary key user_portfolio_name', max_length=150, unique=True)),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(help_text='User portfolio name', max_length=20)),
                ('create_date', models.DateField(auto_now_add=True, help_text='Date of portfolio creation')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=10000.0, help_text='Start balance 10k PLN', max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(help_text='Company Abbreviation', max_length=10)),
                ('amount', models.IntegerField(help_text='Number of stocks in portfolio', validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_price', models.DecimalField(decimal_places=2, help_text='Average stock price', max_digits=15)),
                ('stock_buy_date', models.DateField(auto_now=True, help_text='Date of adding the stock')),
                ('portfolio_id', models.ForeignKey(help_text='Portfolio FK', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.portfolio', to_field='portfolio_id')),
            ],
        ),
    ]
